In [3]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y]) #array([1, 2, 3, 3, 2, 1])
z = np.array([666, 666, 666])
np.concatenate([x, y, z]) #array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [5]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
#0轴表示行，1轴表示列，axis=1表示对列进行操作，一列一列的就是行的方向,对列操作行不变

In [9]:
z.reshape(1, -1)

array([[666, 666, 666]])

In [14]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [15]:
#水平方向上的
B = np.full((2,2), 100)
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割

In [16]:
x = np.arange(10)
x1, x2, x3 = np.split(x, [3, 7])

In [19]:
A = np.arange(16).reshape((4, 4))
A1, A2 = np.split(A, [2])   #axis默认=0针对行的切割,列数是不会变的
A1, A2 = np.split(A, [2], axis=1)  #列的切割 行数是不变的

In [ ]:
upper, lower = np.vsplit(A, [2]) #列不变的切割
left, right = np.hsplit(A, [2])  #行不变的切割

In [20]:
data = np.arange(16).reshape((4, 4))
X, y = np.hsplit(data, [-1])# -号转变切割方便,不再是从前往后