In [6]:
import numpy as np

x = np.arange(2,10,2)
x

array([2, 4, 6, 8])

In [9]:
ind = [1, 2, 3]#根据索引创建值的数组
x[ind]

array([4, 6, 8])

In [3]:
ind = np.array([[0, 2], [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

#### Fancy Indexing 应用在二维数组

In [10]:
x = np.arange(16)
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [13]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
np.count_nonzero( x <= 3) #4  进去的布尔数组中有多少个非0元素 4个true 其他都是false
np.sum(x <= 3)  #传进去的数组中有多少个<3的元素
np.any(x == 0)  # True是否有任何元素 满足条件  '==0' 
np.all(x > 0)   #False 是不是全部的数据都是 大于0 的
np.sum(X % 2 == 0, axis=0)    #array([4, 0, 4, 0]) 在列的方向上 偶数的个数
np.sum((x > 3) & (x < 10))    # >3 <10 的数据个数 注意是 & 不是&& 因为是针对矩阵做与的操作

6

In [19]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
x[x<5]  #array([0, 1, 2, 3, 4, 5])  小于5的数有哪些 返回一个数组
x[x % 2 == 0]  # array([ 0,  2,  4,  6,  8, 10, 12, 14])   偶数有哪些


array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [26]:
#最后的特征值可以被3整除     X[:,3] % 3 == 0 取出索引为3的列的值 中可以被3整除的   行就全部
X[X[:,3] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])