In [41]:
import numpy as np
np.random.seed(0)

x = np.arange(10)
x #array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
X = np.arange(15).reshape((3, 5))
X
#array([[ 0,  1,  2,  3,  4],
#       [ 5,  6,  7,  8,  9],
#       [10, 11, 12, 13, 14]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
#ndim 维度数量 
x.ndim #1
X.ndim #2,两个维度

#具体形状,对于一个数组，其shape属性的长度（length）也既是它的ndim.
x.shape #(10,)
X.shape #(3, 5)

x.size  #10
X.size #15

15

In [50]:
#读取数据
x[1]    #一维数据
X[2,3]  #二维数据访问

13

In [57]:
x[1::2]
x[::-1]
X[0,:]
X[:,0]

array([ 0,  5, 10])