In [1]:
1+2

3

In [1]:
import numpy as np
np.__version__

'1.14.0'

In [11]:
np.zeros(10)
np.zeros(4,dtype=float)
np.zeros((3,4))
np.zeros(shape=(3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.ones(10)
np.ones((3,5))
np.ones(shape=(3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.full((3,5), 66)
np.full(shape=(3,5), fill_value=626)

array([[66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66]])

In [22]:
[i for i in range(2,10, 3)]
np.arange(2,10,3)
np.arange(2,10,0.3)
np.arange(0, 10)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
[i for i in range(2,10, 0.3)]

TypeError: 'float' object cannot be interpreted as an integer

In [27]:
np.linspace(1,10,10)

In [32]:
np.random.randint(0,10) #5 [a, b) 后面是一个闭区间
np.random.randint(0,10,2) #array([7, 3])
np.random.randint(0, 10, size=10) #array([7, 9, 9, 0, 1, 9, 5, 6, 2, 7])
np.random.randint(0, 10, size=(4,6))#创建随机矩阵

array([[6, 5, 9, 0, 3, 0],
       [4, 1, 9, 6, 5, 7],
       [7, 4, 3, 9, 6, 5],
       [9, 9, 8, 2, 4, 1]])

In [40]:
np.random.normal(0,1,3)


array([-0.27164534, -0.56984035,  2.39201391])